spring:
  application:
    name: practice

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3000000

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org.springframework.security: DEBUG
stripe:
  api:
    key: ${STRIPE_API_SECRET_KEY}
